### ISSUE TITLE
keep extensions unique to a filetype or allow duplicates? 

### ISSUE THREAD

**Issue by jaromil** [dyne/file-extension-list#11]
Some extensions are ambiguous: a `.js` may belong to `code` as well to `web` as debated in https://github.com/dyne/file-extension-list/pull/10

This issue is an open question for all those using file-extension-list:
How do you feel about having extensions duplicate across types? Will it break your current applications (if any beyond my own https://github.com/dyne/harvest) or you could handle it?

I pose this question because in my own use the goal is not that of detecting the type of a single file, but of directories that may contain multiple file types; in order to do so I apply a simple fuzzy logic based on file-types (see: https://github.com/dyne/harvest/blob/master/harvest#L56).

**Comment by cs91chris** [comment]
Hi
first of all, thanks for the useful resource.

My 2 cents,
in my use case the goal is detecting the type of a single file. For example the topology "text" is ambiguous for me because I need to distinguish between plain text files from document files like doc or pdf. So in my case I may need another topology with or without duplicates.

I think that if you want that this is for general purpose, It should allows duplicates, otherwise, if you want satisfy your goal for harvest, you should update the doc because: "It can be used by any program to quickly distinguish between file types" it's not clear and seems close to my case.

**Comment by jaromil** [comment]
Yes, after re-reading comments in #10 I realize what you say and it makes sense. I think both use-cases are important and while the non-dupes may be simpler it definitely is the most needed, justifying even more the existence of this repository.

I will add a simple spec: a `%` will follow extension names that are duplicates in a secondary position, so that one can parse them away if so is desired. I believe this way also a parser can keep being simple: adopting a configuration file of sorts would increase too much the complexity.
